// packages/webapp/src/routes/login.tsx
import { Button } from '@heroui/react';
import { createFileRoute, redirect, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { authClient } from '@/lib/auth-client';
import { fetchSession } from '@/lib/session';

export const Route = createFileRoute('/login')({
    beforeLoad: async () => {
        const session = await fetchSession();
        if (session) throw redirect({ to: '/chat', search: {} });
    },
    component: LoginPage,
});

function LoginPage() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        setLoading(true);
        const { error: signInError } = await authClient.signIn.email({ email, password });
        setLoading(false);
        if (signInError) {
            setError(signInError.message ?? '登录失败，请检查邮箱和密码');
            return;
        }
        window.location.href = '/chat';
    };

    return (
        <div className='flex min-h-dvh items-center justify-center bg-gray-50 p-6'>
            <div className='w-full max-w-sm rounded-2xl border border-gray-200 bg-white p-8 shadow-sm'>
                <h1 className='text-2xl font-bold text-gray-900'>登录</h1>
                <p className='mt-1 text-sm text-gray-500'>与智能体对话，从这里开始。</p>
                <form className='mt-6 space-y-4' onSubmit={handleSubmit}>
                    <div>
                        <label className='mb-1 block text-sm font-medium text-gray-700' htmlFor='email'>
                            邮箱
                        </label>
                        <input
                            id='email'
                            type='email'
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
                            placeholder='you@example.com'
                        />
                    </div>
                    <div>
                        <label className='mb-1 block text-sm font-medium text-gray-700' htmlFor='password'>
                            密码
                        </label>
                        <input
                            id='password'
                            type='password'
                            required
                            minLength={8}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
                            placeholder='至少 8 位'
                        />
                    </div>
                    {error ? <p className='text-sm text-red-600'>{error}</p> : null}
                    <Button type='submit' fullWidth isDisabled={loading}>
                        {loading ? '登录中…' : '登录'}
                    </Button>
                </form>
                <p className='mt-4 text-center text-sm text-gray-500'>
                    还没有账号？{' '}
                    <Link to='/register' className='font-medium text-blue-600 hover:underline'>
                        立即注册
                    </Link>
                </p>
            </div>
        </div>
    );
}

// packages/webapp/app/pages/login.vue
<script setup lang="ts">
import { extractApiError } from '@contract';
import { useI18n } from 'vue-i18n';

definePageMeta({ middleware: 'guest' });

const { t } = useI18n();

const email = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);
const wechatEnabled = ref(false);
const route = useRoute();

onMounted(async () => {
    try {
        const res = await $fetch<{ enabled: boolean }>('/api/auth/wechat/status');
        wechatEnabled.value = res.enabled;
    } catch {
        wechatEnabled.value = false;
    }
});

async function submit() {
    error.value = '';
    loading.value = true;
    const { error: err } = await authClient.signIn.email({ email: email.value, password: password.value });
    loading.value = false;
    if (err) {
        error.value = extractApiError(err, t('common.error'));
        return;
    }
    await navigateTo((route.query.redirect as string) || '/chat');
}

function loginWithWechat() {
    const redirect = encodeURIComponent((route.query.redirect as string) || '/chat');
    window.location.href = `/api/auth/wechat?redirect=${redirect}`;
}
</script>

<template>
    <div class="mx-auto mt-10 w-full max-w-md">
        <div class="app-card overflow-hidden">
            <!-- 顶部品牌区 -->
            <div class="bg-brand-gradient px-8 py-7 text-center">
                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 text-xl font-black backdrop-blur-sm">EE</div>
                <h1 class="mt-3 text-xl font-black">{{ t('nav.login') }}</h1>
                <p class="mt-1 text-xs opacity-85">欢迎回到 {{ t('common.appName') }}</p>
            </div>

            <div class="p-8">
                <form class="space-y-4" @submit.prevent="submit">
                    <div>
                        <label class="text-soft mb-1.5 block text-xs font-bold">{{ t('profile.email') }}</label>
                        <input v-model="email" type="email" required autocomplete="email" class="app-input" placeholder="you@example.com" />
                    </div>
                    <div>
                        <label class="text-soft mb-1.5 block text-xs font-bold">密码</label>
                        <input v-model="password" type="password" required autocomplete="current-password" class="app-input" placeholder="••••••••" />
                    </div>

                    <p v-if="error" class="app-alert app-alert-danger">{{ error }}</p>

                    <button type="submit" :disabled="loading" class="app-btn app-btn-primary w-full !py-3">
                        {{ loading ? t('common.loading') : t('nav.login') }}
                    </button>
                </form>

                <div v-if="wechatEnabled" class="mt-6">
                    <div class="relative my-4">
                        <div class="absolute inset-0 flex items-center"><div class="app-divider w-full border-t-0" /></div>
                        <div class="relative flex justify-center text-[10px] uppercase">
                            <span class="text-faint px-2" style="background-color: var(--surface)">OR</span>
                        </div>
                    </div>
                    <button type="button" class="app-btn app-btn-outline w-full !py-3" @click="loginWithWechat">
                        <span>💬</span>
                        <span>微信一键登录</span>
                    </button>
                </div>

                <p class="text-muted-2 mt-6 text-center text-xs">
                    还没有账号？
                    <NuxtLink to="/register" class="app-link">{{ t('nav.register') }}</NuxtLink>
                </p>
            </div>
        </div>
    </div>
</template>
