// packages/webapp/src/routes/register.tsx
import { Button } from '@heroui/react';
import { createFileRoute, redirect, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { authClient } from '@/lib/auth-client';
import { fetchSession } from '@/lib/session';

export const Route = createFileRoute('/register')({
    beforeLoad: async () => {
        const session = await fetchSession();
        if (session) throw redirect({ to: '/chat', search: {} });
    },
    component: RegisterPage,
});

function RegisterPage() {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        setLoading(true);
        const { error: signUpError } = await authClient.signUp.email({
            name: name || email.split('@')[0] || '用户',
            email,
            password,
        });
        setLoading(false);
        if (signUpError) {
            setError(signUpError.message ?? '注册失败，请稍后再试');
            return;
        }
        window.location.href = '/chat';
    };

    return (
        <div className='flex min-h-dvh items-center justify-center bg-gray-50 p-6'>
            <div className='w-full max-w-sm rounded-2xl border border-gray-200 bg-white p-8 shadow-sm'>
                <h1 className='text-2xl font-bold text-gray-900'>注册</h1>
                <p className='mt-1 text-sm text-gray-500'>创建账号，开始与智能体对话。</p>
                <form className='mt-6 space-y-4' onSubmit={handleSubmit}>
                    <div>
                        <label className='mb-1 block text-sm font-medium text-gray-700' htmlFor='name'>
                            昵称
                        </label>
                        <input
                            id='name'
                            type='text'
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
                            placeholder='可选'
                        />
                    </div>
                    <div>
                        <label className='mb-1 block text-sm font-medium text-gray-700' htmlFor='email'>
                            邮箱
                        </label>
                        <input
                            id='email'
                            type='email'
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
                            placeholder='you@example.com'
                        />
                    </div>
                    <div>
                        <label className='mb-1 block text-sm font-medium text-gray-700' htmlFor='password'>
                            密码
                        </label>
                        <input
                            id='password'
                            type='password'
                            required
                            minLength={8}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
                            placeholder='至少 8 位'
                        />
                    </div>
                    {error ? <p className='text-sm text-red-600'>{error}</p> : null}
                    <Button type='submit' fullWidth isDisabled={loading}>
                        {loading ? '注册中…' : '注册'}
                    </Button>
                </form>
                <p className='mt-4 text-center text-sm text-gray-500'>
                    已有账号？{' '}
                    <Link to='/login' className='font-medium text-blue-600 hover:underline'>
                        直接登录
                    </Link>
                </p>
            </div>
        </div>
    );
}

// packages/webapp/app/pages/register.vue
<script setup lang="ts">
import { extractApiError } from '@contract';
import { useI18n } from 'vue-i18n';

definePageMeta({ middleware: 'guest' });

const { t } = useI18n();

const name = ref('');
const email = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

async function submit() {
    error.value = '';
    loading.value = true;
    const { error: err } = await authClient.signUp.email({
        name: name.value,
        email: email.value,
        password: password.value,
    });
    loading.value = false;
    if (err) {
        error.value = extractApiError(err, t('common.error'));
        return;
    }
    await navigateTo('/chat');
}
</script>

<template>
    <div class="mx-auto mt-10 w-full max-w-md">
        <div class="app-card overflow-hidden">
            <div class="bg-brand-gradient px-8 py-7 text-center">
                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 text-xl font-black backdrop-blur-sm">EE</div>
                <h1 class="mt-3 text-xl font-black">{{ t('nav.register') }}</h1>
                <p class="mt-1 text-xs opacity-85">开启你的智能体数字化身旅程</p>
            </div>

            <div class="p-8">
                <form class="space-y-4" @submit.prevent="submit">
                    <div>
                        <label class="text-soft mb-1.5 block text-xs font-bold">昵称 / Username</label>
                        <input v-model="name" type="text" required autocomplete="nickname" class="app-input" placeholder="你的昵称" />
                    </div>
                    <div>
                        <label class="text-soft mb-1.5 block text-xs font-bold">{{ t('profile.email') }}</label>
                        <input v-model="email" type="email" required autocomplete="email" class="app-input" placeholder="you@example.com" />
                    </div>
                    <div>
                        <label class="text-soft mb-1.5 block text-xs font-bold">密码 / Password（≥8 位）</label>
                        <input v-model="password" type="password" required minlength="8" autocomplete="new-password" class="app-input" placeholder="••••••••" />
                    </div>

                    <p v-if="error" class="app-alert app-alert-danger">{{ error }}</p>

                    <button type="submit" :disabled="loading" class="app-btn app-btn-primary w-full !py-3">
                        {{ loading ? t('common.loading') : t('nav.register') }}
                    </button>
                </form>

                <p class="text-muted-2 mt-6 text-center text-xs">
                    已有账号？
                    <NuxtLink to="/login" class="app-link">{{ t('nav.login') }}</NuxtLink>
                </p>
            </div>
        </div>
    </div>
</template>
