// packages/webapp/app/pages/pricing.vue
<script setup lang="ts">
import {
    extractApiError,
    formatDate,
    formatYuan,
    quotaUsedPercent,
    type CreateOrderResponse,
    type JsapiParams,
    type MembershipStatus,
    type OrderRecord,
    type PlansResponse,
    type Plan,
} from '@contract';
import QRCode from 'qrcode';
import { useI18n } from 'vue-i18n';

definePageMeta({ middleware: 'auth' });

const { t } = useI18n();

const statusData = ref<MembershipStatus | null>(null);
const plans = ref<Plan[]>([]);
const orders = ref<OrderRecord[]>([]);
const period = ref<'monthly' | 'yearly'>('monthly');

// 支付弹窗状态
const showPayModal = ref(false);
const activeOrder = ref<CreateOrderResponse | null>(null);
const qrDataUrl = ref<string>('');
const pollingTimer = ref<ReturnType<typeof setInterval> | null>(null);
const paySuccess = ref(false);
const paying = ref(false);
const payError = ref('');

async function loadData() {
    try {
        const [mStatus, pData, oData] = await Promise.all([
            $fetch<MembershipStatus>('/api/billing/membership'),
            $fetch<PlansResponse>('/api/plans'),
            $fetch<{ orders: OrderRecord[] }>('/api/billing/orders'),
        ]);
        statusData.value = mStatus;
        plans.value = pData.plans;
        orders.value = oData.orders;
    } catch (e) {
        console.error('加载会员数据失败:', e);
    }
}

onMounted(loadData);
onUnmounted(stopPolling);

function stopPolling() {
    if (pollingTimer.value) {
        clearInterval(pollingTimer.value);
        pollingTimer.value = null;
    }
}

function startPolling(orderNo: string) {
    stopPolling();
    pollingTimer.value = setInterval(async () => {
        try {
            const res = await $fetch<{ status: string }>(`/api/billing/orders/${orderNo}`);
            if (res.status === 'paid') {
                stopPolling();
                paySuccess.value = true;
                await loadData();
                setTimeout(closePayModal, 1800);
            } else if (res.status === 'closed') {
                stopPolling();
                payError.value = t('billing.payFailed');
            }
        } catch (e) {
            console.error('轮询订单状态失败:', e);
        }
    }, 2000);
}

/** 微信内浏览器 JSAPI 支付 */
function invokeWeixinJsapi(params: JsapiParams) {
    const bridge = (window as any).WeixinJSBridge;
    if (!bridge) {
        payError.value = '请在微信内打开以完成支付';
        return;
    }
    bridge.invoke('getBrandWCPayRequest', params, (res: { err_msg?: string }) => {
        if (res?.err_msg === 'get_brand_wcpay_request:ok') {
            paySuccess.value = true;
            loadData();
            setTimeout(closePayModal, 1800);
        } else if (res?.err_msg !== 'get_brand_wcpay_request:cancel') {
            payError.value = t('billing.payFailed');
        }
    });
}

async function handleBuy(plan: Plan) {
    if (plan.code === 'free') return;
    paying.value = true;
    payError.value = '';
    try {
        const res = await $fetch<CreateOrderResponse>('/api/billing/orders', {
            method: 'POST',
            body: { planId: plan.id, period: period.value },
        });
        activeOrder.value = res;
        paySuccess.value = false;
        showPayModal.value = true;

        if (res.mode === 'qrcode' && res.payUrl) {
            qrDataUrl.value = await QRCode.toDataURL(res.payUrl, { width: 220, margin: 1 });
            startPolling(res.orderNo);
        } else if (res.mode === 'mock') {
            startPolling(res.orderNo);
        } else if (res.mode === 'jsapi' && res.jsapiParams) {
            invokeWeixinJsapi(res.jsapiParams);
            startPolling(res.orderNo);
        } else if (res.mode === 'redirect' && res.payUrl) {
            window.location.href = res.payUrl;
        }
    } catch (e) {
        alert(extractApiError(e, t('common.error')));
    } finally {
        paying.value = false;
    }
}

async function handleMockPay() {
    if (!activeOrder.value) return;
    try {
        await $fetch(`/api/billing/orders/${activeOrder.value.orderNo}/mock-pay`, { method: 'POST' });
    } catch (e) {
        payError.value = extractApiError(e, t('common.error'));
    }
}

function closePayModal() {
    stopPolling();
    showPayModal.value = false;
    activeOrder.value = null;
    qrDataUrl.value = '';
    paySuccess.value = false;
    payError.value = '';
}

const usedPercent = computed(() => quotaUsedPercent(statusData.value?.usedToday, statusData.value?.chatQuotaPerDay));

const statusTone: Record<string, string> = {
    paid: 'app-badge-success',
    pending: 'app-badge-warning',
    closed: 'app-badge-neutral',
    refunded: 'app-badge-info',
};

function orderStatusText(status: string): string {
    if (status === 'paid') return t('billing.statusPaid');
    if (status === 'pending') return t('billing.statusPending');
    return t('billing.statusClosed');
}
</script>

<template>
    <div class="space-y-9">
        <!-- 头部标题 -->
        <div class="mx-auto max-w-2xl text-center">
            <h1 class="text-3xl font-black tracking-tight sm:text-4xl">{{ t('billing.title') }}</h1>
            <p class="text-muted-2 mt-2 text-sm">{{ t('billing.subtitle') }}</p>
        </div>

        <!-- 当前会员状态卡片 -->
        <div v-if="statusData" class="app-card p-6 sm:p-8">
            <div class="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <div class="flex flex-wrap items-center gap-3">
                        <span class="text-xl font-bold"> {{ t('billing.myPlan') }}：{{ statusData.plan?.name || t('billing.freePlan') }} </span>
                        <span :class="['app-badge', statusData.expiresAt ? 'app-badge-success' : 'app-badge-neutral']">
                            {{ statusData.expiresAt ? t('common.enabled') : t('billing.currentPlan') }}
                        </span>
                    </div>
                    <p class="text-faint mt-1.5 text-xs">
                        {{ statusData.expiresAt ? `${t('billing.expiresAt')}：${formatDate(statusData.expiresAt)}` : t('billing.unlimited') }}
                    </p>
                </div>

                <div class="min-w-[220px]">
                    <div class="text-soft mb-1.5 flex items-center justify-between text-xs font-semibold">
                        <span>{{ t('billing.usedToday') }}</span>
                        <span class="font-bold"> {{ statusData.usedToday }} / {{ statusData.chatQuotaPerDay ?? '∞' }} </span>
                    </div>
                    <div class="app-progress">
                        <div class="app-progress-bar" :style="{ width: `${statusData.chatQuotaPerDay === null ? 100 : usedPercent}%` }" />
                    </div>
                </div>
            </div>
        </div>

        <!-- 月付 / 年付 切换 -->
        <div class="flex justify-center">
            <div class="app-panel inline-flex gap-1 p-1.5">
                <button :class="['app-btn', period === 'monthly' ? 'app-btn-soft' : 'app-btn-ghost']" @click="period = 'monthly'">
                    {{ t('billing.monthly') }}
                </button>
                <button :class="['app-btn', period === 'yearly' ? 'app-btn-soft' : 'app-btn-ghost']" @click="period = 'yearly'">
                    <span>{{ t('billing.yearly') }}</span>
                    <span class="app-chip app-chip-brand text-[10px]">-20%</span>
                </button>
            </div>
        </div>

        <!-- 套餐卡片网格 -->
        <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
            <div
                v-for="p in plans"
                :key="p.id"
                :class="['app-card relative flex flex-col justify-between p-6 sm:p-8', p.code === statusData?.plan?.code ? 'border-brand ring-brand' : '']"
            >
                <div
                    v-if="p.code === 'pro'"
                    class="bg-brand-gradient absolute -top-3 left-1/2 -translate-x-1/2 rounded-full px-3 py-0.5 text-[10px] font-black tracking-wider uppercase shadow-xs"
                >
                    POPULAR
                </div>

                <div>
                    <div class="flex items-center justify-between">
                        <h3 class="text-xl font-black">{{ p.name }}</h3>
                        <span v-if="p.code === statusData?.plan?.code" class="app-badge app-badge-success">{{ t('billing.currentPlan') }}</span>
                    </div>
                    <p class="text-muted-2 mt-2 min-h-[36px] text-xs leading-relaxed">{{ p.description }}</p>

                    <div class="mt-6 flex items-baseline gap-1">
                        <span class="text-3xl font-black"> ¥{{ period === 'yearly' ? formatYuan(p.yearlyPriceCents) : formatYuan(p.monthlyPriceCents) }} </span>
                        <span class="text-faint text-xs font-medium">{{ period === 'yearly' ? t('billing.perYear') : t('billing.perMonth') }}</span>
                    </div>

                    <ul class="text-soft mt-6 space-y-3 text-xs">
                        <li class="flex items-center gap-2">
                            <span class="text-brand font-bold">✓</span>
                            <span
                                >{{ t('billing.dailyQuota') }}：<strong>{{ p.chatQuotaPerDay ?? t('billing.unlimited') }}</strong></span
                            >
                        </li>
                        <li class="flex items-center gap-2">
                            <span class="text-brand font-bold">✓</span>
                            <span>ReAct 智能体多步推理调度</span>
                        </li>
                        <li class="flex items-center gap-2">
                            <span class="text-brand font-bold">✓</span>
                            <span>MCP 服务器与 Generative UI 渲染</span>
                        </li>
                    </ul>
                </div>

                <div class="mt-8">
                    <button v-if="p.code === statusData?.plan?.code" disabled class="app-btn app-btn-outline w-full">
                        {{ t('billing.currentPlan') }}
                    </button>
                    <button v-else :disabled="paying" class="app-btn app-btn-primary w-full !py-3" @click="handleBuy(p)">
                        {{ p.code === 'free' ? t('billing.freePlan') : t('billing.buyNow') }}
                    </button>
                </div>
            </div>
        </div>

        <!-- 支付弹窗 Modal -->
        <div
            v-if="showPayModal"
            class="fixed inset-0 z-50 flex items-center justify-center p-4"
            style="background-color: rgb(15 23 42 / 0.5); backdrop-filter: blur(4px)"
        >
            <div class="app-card w-full max-w-md p-6 sm:p-8">
                <div class="app-divider flex items-center justify-between border-t-0 pb-3">
                    <h3 class="text-base font-bold">{{ t('billing.payMethod') }}</h3>
                    <button class="app-btn app-btn-ghost !px-2" @click="closePayModal">✕</button>
                </div>

                <div class="py-6 text-center">
                    <template v-if="paySuccess">
                        <div class="text-brand mb-2 text-5xl">✓</div>
                        <h4 class="text-lg font-bold">{{ t('billing.paySuccess') }}</h4>
                    </template>

                    <template v-else>
                        <p class="text-muted-2 text-xs">
                            {{ t('billing.orderNo') }}：<span class="font-mono">{{ activeOrder?.orderNo }}</span>
                        </p>
                        <p class="mt-2 text-2xl font-black">¥{{ formatYuan(activeOrder?.amountCents) }}</p>

                        <div v-if="activeOrder?.mode === 'qrcode' && qrDataUrl" class="my-4 flex flex-col items-center">
                            <img :src="qrDataUrl" alt="WeChat Pay QR" class="h-48 w-48 rounded-2xl border p-2" style="border-color: var(--line)" />
                            <p class="text-faint mt-2 text-xs">{{ t('billing.scanToPay') }}</p>
                        </div>

                        <div v-if="activeOrder?.mode === 'mock'" class="app-alert app-alert-warning my-4 text-left">
                            <p class="text-xs font-bold">🛠️ {{ t('billing.mockPay') }}</p>
                            <p class="mt-1 text-[11px] opacity-90">沙箱开发环境，点击下方按钮一键完成模拟开通：</p>
                            <button class="app-btn app-btn-soft mt-3 w-full" @click="handleMockPay">确认模拟支付</button>
                        </div>

                        <p v-if="payError" class="app-alert app-alert-danger mt-3">{{ payError }}</p>

                        <div class="text-faint mt-4 flex items-center justify-center gap-2 text-xs">
                            <span class="bg-brand inline-block h-2 w-2 animate-ping rounded-full" />
                            {{ t('billing.paying') }}
                        </div>
                    </template>
                </div>

                <div class="app-divider flex justify-end pt-3">
                    <button class="app-btn app-btn-outline" @click="closePayModal">{{ t('common.close') }}</button>
                </div>
            </div>
        </div>

        <!-- 常见问题解答 FAQ -->
        <div class="app-card space-y-4 p-6 sm:p-8">
            <div class="text-center sm:text-left">
                <h3 class="flex items-center gap-2 text-lg font-black">
                    <span>❓</span>
                    <span>{{ t('billing.faqTitle') }}</span>
                </h3>
                <p class="text-faint mt-1 text-xs">关于会员方案、每日额度重置与权益退订的常见疑问</p>
            </div>
            <div class="grid grid-cols-1 gap-4 pt-2 md:grid-cols-2">
                <div class="border-line bg-surface-2/60 rounded-2xl border p-4">
                    <p class="text-default text-sm font-bold">💡 {{ t('billing.faq1Q') }}</p>
                    <p class="text-muted-2 mt-2 text-xs leading-relaxed">{{ t('billing.faq1A') }}</p>
                </div>
                <div class="border-line bg-surface-2/60 rounded-2xl border p-4">
                    <p class="text-default text-sm font-bold">💳 {{ t('billing.faq2Q') }}</p>
                    <p class="text-muted-2 mt-2 text-xs leading-relaxed">{{ t('billing.faq2A') }}</p>
                </div>
            </div>
        </div>

        <!-- 历史订单记录 -->
        <div class="app-card p-6 sm:p-8">
            <h3 class="text-lg font-black">{{ t('nav.orders') }}</h3>
            <p class="text-faint mt-0.5 text-xs">查看最近的会员购买记录与开通状态</p>

            <div class="mt-4 overflow-x-auto">
                <table class="app-table">
                    <thead>
                        <tr>
                            <th>{{ t('billing.orderNo') }}</th>
                            <th>{{ t('nav.plans') }}</th>
                            <th>周期</th>
                            <th>{{ t('billing.amount') }}</th>
                            <th>渠道</th>
                            <th>{{ t('common.status') }}</th>
                            <th>时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="o in orders" :key="o.id">
                            <td class="text-muted-2 font-mono text-[11px]">{{ o.orderNo }}</td>
                            <td class="font-semibold">{{ o.planCode }}</td>
                            <td class="text-soft">{{ o.period === 'yearly' ? t('billing.yearly') : t('billing.monthly') }}</td>
                            <td class="font-bold">¥{{ formatYuan(o.amountCents) }}</td>
                            <td class="text-soft">{{ o.provider === 'wechat' ? t('billing.wechatPay') : t('billing.mockPay') }}</td>
                            <td>
                                <span :class="['app-badge', statusTone[o.status] ?? 'app-badge-neutral']">{{ orderStatusText(o.status) }}</span>
                            </td>
                            <td class="text-faint">{{ formatDate(o.createdAt) }}</td>
                        </tr>
                        <tr v-if="!orders.length">
                            <td colspan="7" class="text-faint py-8 text-center text-xs">{{ t('admin.tableEmpty') }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</template>

// packages/webapp/src/routes/pricing.tsx
import type { SessionUser } from '@/components/app-header';
import { AppHeader } from '@/components/app-header';
import i18n from '@/i18n';
import { api } from '@/lib/client-api';
import { fetchSession } from '@/lib/session';
import { Button } from '@heroui/react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { createFileRoute, redirect } from '@tanstack/react-router';
import type { TFunction } from 'i18next';
import { QRCodeSVG } from 'qrcode.react';
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';

interface Plan {
    id: number;
    code: string;
    name: string;
    description: string;
    chatQuotaPerDay: number | null;
    monthlyPriceCents: number;
    yearlyPriceCents: number | null;
    enabled: boolean;
    sortOrder: number;
}

interface MembershipStatus {
    plan: Plan | null;
    expiresAt: string | null;
    chatQuotaPerDay: number | null;
    usedToday: number;
}

interface CreateOrderResult {
    orderNo: string;
    status: 'pending' | 'paid' | 'closed';
    provider: string;
    mode: 'mock' | 'qrcode' | 'jsapi' | 'redirect';
    payUrl?: string | null;
    jsapiParams?: {
        appId: string;
        timeStamp: string;
        nonceStr: string;
        package: string;
        signType: 'RSA';
        paySign: string;
    };
    amountCents: number;
    planCode: string;
    period: 'monthly' | 'yearly';
}

interface OrderStatusResult {
    orderNo: string;
    status: 'pending' | 'paid' | 'closed' | 'refunded';
    mode: string | null;
    payUrl: string | null;
    amountCents: number;
}

interface OrderRow {
    id: number;
    orderNo: string;
    planCode: string;
    period: string;
    amountCents: number;
    status: string;
    provider: string;
    paidAt: string | null;
    createdAt: string;
}

const PERIOD_KEYS: Record<string, string> = { monthly: 'pricing.periodMonthly', yearly: 'pricing.periodYearly' };
const STATUS_KEYS: Record<string, string> = { pending: 'pricing.statusPending', paid: 'pricing.statusPaid', closed: 'pricing.statusClosed', refunded: 'pricing.statusRefunded' };
const PROVIDER_KEYS: Record<string, string> = { wechat: 'pricing.providerWechat', mock: 'pricing.providerMock' };

/** 枚举值 → 文案：命中映射表时走 i18n，否则原样展示原始值 */
function labelFor(t: TFunction, keys: Record<string, string>, value: string) {
    const key = keys[value];
    return key ? t(key) : value;
}

/** 金额展示：分 → 元（保留 2 位小数） */
function yuan(cents: number) {
    return (cents / 100).toFixed(2);
}

function formatDateTime(value: string | null) {
    if (!value) return '—';
    const locale = i18n.language?.startsWith('zh') ? 'zh-CN' : 'en-US';
    return new Date(value).toLocaleString(locale, { hour12: false });
}

export const Route = createFileRoute('/pricing')({
    beforeLoad: async () => {
        const session = await fetchSession();
        if (!session) throw redirect({ to: '/login', search: {} });
        return { session };
    },
    component: PricingPage,
});

function PricingPage() {
    const { t } = useTranslation();
    const { session } = Route.useRouteContext();
    const user = session.user as SessionUser;

    const { data: membership } = useQuery({
        queryKey: ['billing', 'membership'],
        queryFn: () => api<MembershipStatus>('/api/billing/membership'),
    });

    const { data: planData, isLoading: plansLoading } = useQuery({
        queryKey: ['plans'],
        queryFn: () => api<{ plans: Plan[]; providers: { code: string; available: boolean }[] }>('/api/plans'),
    });

    const { data: myOrders, isLoading: ordersLoading } = useQuery({
        queryKey: ['billing', 'orders'],
        queryFn: () => api<{ orders: OrderRow[] }>('/api/billing/orders'),
    });

    const plans = planData?.plans ?? [];
    const orders = myOrders?.orders ?? [];
    const currentPlanId = membership?.plan?.id ?? null;

    const [payModal, setPayModal] = useState<{ plan: Plan; period: 'monthly' | 'yearly'; order: CreateOrderResult } | null>(null);
    const [buying, setBuying] = useState<string | null>(null);
    const [orderError, setOrderError] = useState<string | null>(null);

    const handleBuy = async (plan: Plan, period: 'monthly' | 'yearly') => {
        setBuying(`${plan.id}:${period}`);
        setOrderError(null);
        try {
            const order = await api<CreateOrderResult>('/api/billing/orders', {
                method: 'POST',
                body: JSON.stringify({ planId: plan.id, period }),
            });
            setPayModal({ plan, period, order });
        } catch (err) {
            setOrderError(err instanceof Error ? err.message : t('pricing.orderErrorFallback'));
        } finally {
            setBuying(null);
        }
    };

    return (
        <div className='flex min-h-dvh flex-col bg-gray-50'>
            <AppHeader user={user} />
            <main className='mx-auto w-full max-w-5xl flex-1 space-y-6 p-6'>
                {/* 当前会员状态 */}
                <section className='rounded-2xl border border-gray-200 bg-white p-6 shadow-sm'>
                    <div className='flex flex-wrap items-center justify-between gap-4'>
                        <div>
                            <p className='text-sm text-gray-500'>{t('pricing.currentPlan')}</p>
                            <p className='mt-1 text-xl font-bold text-gray-900'>{membership?.plan?.name ?? t('pricing.noPlan')}</p>
                            <p className='mt-1 text-sm text-gray-500'>
                                {membership?.expiresAt
                                    ? t('pricing.expiresAt', { date: formatDateTime(membership.expiresAt) })
                                    : t('pricing.noActiveMembership')}
                            </p>
                        </div>
                        <div className='text-right'>
                            <p className='text-sm text-gray-500'>{t('pricing.todayUsage')}</p>
                            <p className='mt-1 text-xl font-bold text-gray-900'>
                                {membership ? membership.usedToday : '—'}
                                <span className='text-sm font-normal text-gray-400'> / {membership?.chatQuotaPerDay ?? '∞'}</span>
                            </p>
                        </div>
                    </div>
                </section>

                {/* 套餐列表 */}
                <section className='space-y-3'>
                    <div>
                        <h2 className='text-lg font-bold text-gray-900'>{t('pricing.choosePlan')}</h2>
                        {orderError ? <p className='mt-1 text-sm text-red-600'>{orderError}</p> : null}
                    </div>
                    <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>
                        {plans.map((plan) => (
                            <PlanCard
                                key={plan.id}
                                plan={plan}
                                current={currentPlanId === plan.id}
                                buying={buying !== null}
                                onBuy={(period) => void handleBuy(plan, period)}
                            />
                        ))}
                        {!plansLoading && plans.length === 0 ? <p className='text-sm text-gray-400'>{t('pricing.noPlans')}</p> : null}
                    </div>
                </section>

                {/* 我的订单 */}
                <section className='space-y-3'>
                    <h2 className='text-lg font-bold text-gray-900'>{t('pricing.myOrders')}</h2>
                    <div className='overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm'>
                        <table className='w-full text-sm'>
                            <thead className='bg-gray-50 text-left text-xs text-gray-500 uppercase'>
                                <tr>
                                    <th className='px-4 py-3'>{t('pricing.orderNo')}</th>
                                    <th className='px-4 py-3'>{t('pricing.plan')}</th>
                                    <th className='px-4 py-3'>{t('pricing.period')}</th>
                                    <th className='px-4 py-3'>{t('pricing.amount')}</th>
                                    <th className='px-4 py-3'>{t('pricing.status')}</th>
                                    <th className='px-4 py-3'>{t('pricing.channel')}</th>
                                    <th className='px-4 py-3'>{t('pricing.paidAt')}</th>
                                </tr>
                            </thead>
                            <tbody className='divide-y divide-gray-100'>
                                {orders.map((order) => (
                                    <tr key={order.id}>
                                        <td className='px-4 py-3 font-mono text-xs text-gray-500'>{order.orderNo}</td>
                                        <td className='px-4 py-3 text-gray-900'>{order.planCode}</td>
                                        <td className='px-4 py-3 text-gray-600'>{labelFor(t, PERIOD_KEYS, order.period)}</td>
                                        <td className='px-4 py-3 text-gray-900'>¥{yuan(order.amountCents)}</td>
                                        <td className='px-4 py-3'>
                                            <span
                                                className={`rounded-full px-2 py-0.5 text-xs ${
                                                    order.status === 'paid'
                                                        ? 'bg-emerald-100 text-emerald-700'
                                                        : order.status === 'pending'
                                                          ? 'bg-amber-100 text-amber-700'
                                                          : 'bg-gray-100 text-gray-500'
                                                }`}
                                            >
                                                {labelFor(t, STATUS_KEYS, order.status)}
                                            </span>
                                        </td>
                                        <td className='px-4 py-3 text-gray-600'>{labelFor(t, PROVIDER_KEYS, order.provider)}</td>
                                        <td className='px-4 py-3 text-gray-500'>{formatDateTime(order.paidAt)}</td>
                                    </tr>
                                ))}
                                {!ordersLoading && orders.length === 0 ? (
                                    <tr>
                                        <td colSpan={7} className='px-4 py-8 text-center text-gray-400'>
                                            {t('pricing.noOrders')}
                                        </td>
                                    </tr>
                                ) : null}
                            </tbody>
                        </table>
                    </div>
                </section>
            </main>

            {payModal ? <PayModal payModal={payModal} onClose={() => setPayModal(null)} /> : null}
        </div>
    );
}

function PlanCard({ plan, current, buying, onBuy }: { plan: Plan; current: boolean; buying: boolean; onBuy: (period: 'monthly' | 'yearly') => void }) {
    const { t } = useTranslation();
    const isFree = plan.code === 'free' || plan.monthlyPriceCents === 0;

    return (
        <div
            className={`flex flex-col rounded-2xl border bg-white p-5 shadow-sm ${
                current ? 'border-blue-500 ring-2 ring-blue-100' : 'border-gray-200'
            }`}
        >
            <div className='flex items-center justify-between'>
                <h3 className='text-base font-bold text-gray-900'>{plan.name}</h3>
                {current ? <span className='rounded-full bg-blue-50 px-2 py-0.5 text-xs text-blue-600'>{t('pricing.currentPlan')}</span> : null}
            </div>
            <p className='mt-1 min-h-10 text-sm text-gray-500'>{plan.description}</p>
            <div className='mt-3 text-2xl font-bold text-gray-900'>
                ¥{yuan(plan.monthlyPriceCents)}
                <span className='text-sm font-normal text-gray-400'>{t('pricing.perMonth')}</span>
            </div>
            <div className='mt-1 text-sm text-gray-500'>
                {plan.yearlyPriceCents !== null ? (
                    <>
                        ¥{yuan(plan.yearlyPriceCents)}
                        <span className='text-gray-400'>{t('pricing.perYear')}</span>
                    </>
                ) : (
                    '—'
                )}
            </div>
            <div className='mt-3 text-sm text-gray-500'>
                {t('pricing.dailyQuota')}
                <span className='font-medium text-gray-900'>{plan.chatQuotaPerDay ?? '∞'}</span>
            </div>
            <div className='mt-4 flex gap-2 pt-1'>
                {isFree ? (
                    <span className='flex-1 rounded-lg bg-gray-100 px-3 py-2 text-center text-sm text-gray-400'>{t('pricing.freeTier')}</span>
                ) : (
                    <>
                        <Button size='sm' isDisabled={buying} onPress={() => onBuy('monthly')} className='flex-1'>
                            {buying ? t('pricing.ordering') : t('pricing.buyMonthly')}
                        </Button>
                        <Button
                            size='sm'
                            variant='ghost'
                            isDisabled={buying || plan.yearlyPriceCents === null}
                            onPress={() => onBuy('yearly')}
                            className='flex-1'
                        >
                            {t('pricing.buyYearly')}
                        </Button>
                    </>
                )}
            </div>
        </div>
    );
}

function PayModal({
    payModal,
    onClose,
}: {
    payModal: { plan: Plan; period: 'monthly' | 'yearly'; order: CreateOrderResult };
    onClose: () => void;
}) {
    const { t } = useTranslation();
    const queryClient = useQueryClient();
    const { plan, period, order } = payModal;
    const [mockPaying, setMockPaying] = useState(false);
    const [payError, setPayError] = useState<string | null>(null);
    const refreshedRef = useRef(false);
    const jsapiInvokedRef = useRef(false);

    // 待支付订单每 2 秒轮询一次；到达终态或 Modal 关闭（组件卸载）后停止
    const { data: latest } = useQuery({
        queryKey: ['billing', 'order', order.orderNo],
        queryFn: () => api<OrderStatusResult>(`/api/billing/orders/${order.orderNo}`),
        refetchInterval: (query) => {
            const s = query.state.data?.status;
            return s && s !== 'pending' ? false : 2000;
        },
    });

    const status = latest?.status ?? order.status;
    const mode = latest?.mode ?? order.mode;

    // 微信内 JSAPI 支付：拉起 WeixinJSBridge 收银台（幂等，仅一次）
    useEffect(() => {
        if (mode !== 'jsapi' || jsapiInvokedRef.current) return;
        const bridge = (window as { WeixinJSBridge?: { invoke: (api: string, params: string, cb: (res: { err_msg?: string }) => void) => void } }).WeixinJSBridge;
        if (!bridge || !order.jsapiParams) return;
        jsapiInvokedRef.current = true;
        bridge.invoke('getBrandWCPayRequest', JSON.stringify(order.jsapiParams), (res) => {
            if (res?.err_msg && !res.err_msg.includes('ok')) {
                console.warn('[pay] JSAPI 拉起失败:', res.err_msg);
            }
        });
    }, [mode, order.jsapiParams]);

    // 支付成功后刷新会员状态与订单列表（只触发一次）
    useEffect(() => {
        if (status === 'paid' && !refreshedRef.current) {
            refreshedRef.current = true;
            void queryClient.invalidateQueries({ queryKey: ['billing'] });
        }
    }, [status, queryClient]);

    const handleMockPay = async () => {
        setMockPaying(true);
        setPayError(null);
        try {
            await api(`/api/billing/orders/${order.orderNo}/mock-pay`, { method: 'POST' });
            await queryClient.invalidateQueries({ queryKey: ['billing', 'order', order.orderNo] });
        } catch (err) {
            setPayError(err instanceof Error ? err.message : t('pricing.payErrorFallback'));
        } finally {
            setMockPaying(false);
        }
    };

    return (
        <Modal title={t('pricing.checkout')} onClose={onClose}>
            <div className='space-y-4'>
                <div className='space-y-2 rounded-xl bg-gray-50 p-4 text-sm'>
                    <div className='flex justify-between'>
                        <span className='text-gray-500'>{t('pricing.plan')}</span>
                        <span className='font-medium text-gray-900'>
                            {t('pricing.planWithPeriod', { plan: plan.name, period: labelFor(t, PERIOD_KEYS, period) })}
                        </span>
                    </div>
                    <div className='flex justify-between'>
                        <span className='text-gray-500'>{t('pricing.orderNo')}</span>
                        <span className='font-mono text-xs text-gray-600'>{order.orderNo}</span>
                    </div>
                    <div className='flex justify-between'>
                        <span className='text-gray-500'>{t('pricing.amount')}</span>
                        <span className='text-lg font-bold text-gray-900'>¥{yuan(order.amountCents)}</span>
                    </div>
                </div>

                {status === 'paid' ? (
                    <div className='rounded-xl bg-emerald-50 p-4 text-center'>
                        <p className='text-lg font-bold text-emerald-600'>{t('pricing.paySuccess')}</p>
                        <p className='mt-1 text-sm text-emerald-700'>{t('pricing.membershipActive')}</p>
                    </div>
                ) : status === 'closed' ? (
                    <div className='rounded-xl bg-gray-100 p-4 text-center text-sm text-gray-500'>{t('pricing.orderClosed')}</div>
                ) : mode === 'mock' ? (
                    <div className='space-y-3 text-center'>
                        <p className='rounded-xl bg-amber-50 p-3 text-sm text-amber-700'>{t('pricing.mockNotice')}</p>
                        <Button isDisabled={mockPaying} onPress={() => void handleMockPay()}>
                            {mockPaying ? t('pricing.paying') : t('pricing.mockPayButton')}
                        </Button>
                        <p className='text-xs text-gray-400'>{t('pricing.waitingResult')}</p>
                    </div>
                ) : mode === 'qrcode' ? (
                    <div className='space-y-3 text-center'>
                        <p className='text-sm text-gray-600'>{t('pricing.scanQr')}</p>
                        {order.payUrl ? (
                            <div className='flex justify-center rounded-xl border border-gray-200 p-3'>
                                <QRCodeSVG value={order.payUrl} size={180} />
                            </div>
                        ) : (
                            <p className='text-sm text-red-600'>{t('pricing.noQr')}</p>
                        )}
                        <p className='text-xs text-gray-400'>{t('pricing.autoConfirm')}</p>
                    </div>
                ) : mode === 'jsapi' ? (
                    <div className='space-y-3 text-center'>
                        <p className='rounded-xl bg-blue-50 p-3 text-sm text-blue-700'>{t('pricing.payInWechat')}</p>
                        <p className='text-xs text-gray-400'>{t('pricing.autoConfirm')}</p>
                    </div>
                ) : (
                    <div className='space-y-3 text-center'>
                        <p className='text-sm text-gray-600'>{t('pricing.payNewPage')}</p>
                        {order.payUrl ? (
                            <a href={order.payUrl} target='_blank' rel='noreferrer' className='text-sm font-medium text-blue-600 hover:underline'>
                                {t('pricing.openPayPage')}
                            </a>
                        ) : null}
                        <p className='text-xs text-gray-400'>{t('pricing.autoConfirm')}</p>
                    </div>
                )}

                {payError ? <p className='text-sm text-red-600'>{payError}</p> : null}
            </div>
        </Modal>
    );
}

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
    return (
        <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4' onClick={onClose}>
            <div className='max-h-[85dvh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl' onClick={(e) => e.stopPropagation()}>
                <div className='mb-4 flex items-center justify-between'>
                    <h2 className='text-lg font-bold text-gray-900'>{title}</h2>
                    <button type='button' onClick={onClose} className='text-gray-400 hover:text-gray-600'>
                        ✕
                    </button>
                </div>
                {children}
            </div>
        </div>
    );
}
